### ISSUE TITLE
Forum: Create ForumProvider

### ISSUE THREAD

**Issue by carlbarrdahl** [DXgovernance/dxvote#769]
Currently blocked by #789. 

- [ ] Set up Ceramic instance
- [ ] Set up OrbitDB instance (Use existing service)
- [ ] Add to GuildsApp

Create a ForumProvider component which wraps a [`@self.id/react@next`](https://github.com/ceramicstudio/self.id/tree/clay) Provider and instantiates an OrbitDB with a registry database.

This could look something like:

```jsx
const OrbitDB = createContext({});
export const useForum = () => React.useContext(OrbitDB);

function useOrbitDB() {
  // Use same instance of OrbitDB as in the rest of the app
  const { context } = useContext();
  const [state, setState] = useState({});

  useEffect(() => {
    if (context.orbitDBService) {
      // Instantiate OrbitDB and set up Registry DB
      context.orbitDBService.getOrbitDB().then(async (orbitdb) => {
        const registry = await orbitdb.open(dbName, dbConfig);
        registry.load();
        setState({ orbitdb, registry });
      });
    }
  }, [context.orbitDBService]);

  return state;
}
function ForumProvider({ children }) {
  const value = useOrbitDB();
  return (
    <Provider client={client}>
      <OrbitDB.Provider value={value}>{children}</OrbitDB.Provider>
    </Provider>
  );
}
```

More details about implementation can be found in: https://github.com/carlbarrdahl/decentralized-forum
Mainly in the files `providers/Ceramic.tsx` and `providers/Orbit.tsx`.

When this is done we can connect Metamask to Ceramic in #770 and link with OrbitDB in #771.
And then create the Ceramic TileDocuments and updating the Registry DB in #772 and querying for comments and posts in #773.
Finally creating the components for Comment and bringing it all together in #774.
