### ISSUE TITLE
Forum: Create and Update Comment

### ISSUE THREAD

**Issue by carlbarrdahl** [DXgovernance/dxvote#772]
- [x] Compose Component in UI
  - [x] User Address + Avatar
  - [x] Editor
- [x] Create / Update Ceramic TileDocument
- [x] Add / Update OrbitDB Registry

There will be a hook for creating TileDocument and adding it to the OrbitDB Registry. Something like this but with SWR instead:
https://github.com/carlbarrdahl/decentralized-forum/blob/master/src/hooks/forum.ts#L22
